# v1.5: việc theo thời gian thật · chuồng/kho · hạt kinh nghiệm · trứng vàng · thoại pet sự kiện
from playwright.sync_api import sync_playwright
import pathlib, sys, json, datetime, subprocess
GAME='file://'+str(pathlib.Path('index.html').resolve())
F=[]
def ck(n,c,x=''):
    print(('  OK   ' if c else '  HỎNG ')+n+(' · '+str(x) if x!='' else ''))
    if not c: F.append(n)
VN=datetime.timezone(datetime.timedelta(hours=7))
SEEN="S.unl={seen:['n:battle','n:shop','n:egg','s:adv','s:team','s:gear','s:shop','s:fash']};"
SETUP="(()=>{S.onboarded=true;S.lic={grand:true};(document.getElementById('lockscr')||{remove(){}}).remove();S.started=Date.now()-30*864e5;"+SEEN+"S.opsSeen=DB.opsCards.map(c=>c.id);S.ch={done:DB.chapterAll.map(c=>c.id),cur:0};S.bondSeen=[25,50,75,90,100];S.npc={met:true,revealed:true};S.tut.done=true;S.coin=500;window.confirm=()=>true;save();const e=document.getElementById('intro');if(e)e.remove();mount()})()"
def page_at(b, when):
    ctx=b.new_context(viewport={'width':390,'height':844}, timezone_id='Asia/Ho_Chi_Minh'); pg=ctx.new_page(); errs=[]
    pg.on('pageerror',lambda e:errs.append(str(e)[:140]))
    pg.clock.install(time=when)
    pg.add_init_script("localStorage.clear()"); pg.goto(GAME); pg.wait_for_timeout(1500)
    pg.evaluate(SETUP); pg.wait_for_timeout(500)
    return pg, errs
clean="(()=>{BANNER_Q=[];document.querySelectorAll('.bnr').forEach(x=>x.remove());try{closeSheet()}catch(e){}})()"
with sync_playwright() as pw:
    b=pw.chromium.launch()
    print('— việc ngày: 9 giờ sáng —')
    pg,errs=page_at(b, datetime.datetime(2026,10,14,9,0,tzinfo=VN))
    E=lambda j: pg.evaluate(j)
    ck('trình duyệt thử đang ở 9 giờ sáng giờ Việt Nam', E("new Date().getHours()")==9, E("new Date().getHours()"))
    c0=E("S.coin"); E("claim('close')"); ck('9 giờ: chưa tick được "Đóng ca"', E("S.coin")==c0 and not E("S.quest.done.includes('close')"))
    E("claim('open')"); ck('9 giờ: "Mở ca" tick được', E("S.quest.done.includes('open')"))
    E("(()=>{S._qtab='d';go('quest')})()"); pg.wait_for_timeout(300)
    ck('dòng "Đóng ca" mờ, ghi rõ giờ mở', pg.locator('#v-quest .q.qlock').count()==4 and '17:00' in pg.locator('#v-quest').inner_text())
    print('— việc tuần: chạm dồn —')
    E("(()=>{S._qtab='w';go('quest')})()"); pg.wait_for_timeout(300)
    for _ in range(5): E("bumpQuest('W','w_stock')")
    ck('chạm 5 lần "Kiểm kho 3 lần trong tuần": chỉ tính 1', E("S.questW.prog.w_stock")==1 and not E("S.questW.done.includes('w_stock')"), E("S.questW.prog.w_stock"))
    E("bumpQuest('W','w_target')"); ck('9 giờ: việc tuần cuối ngày chưa tính', not E("S.questW.prog.w_target"))
    print('— việc tháng: ngày 14 —')
    c0=E("S.coin"); E("bumpQuest('M','m_count')")
    ck('ngày 14: "Kiểm kê cuối tháng" chưa mở, không nhận trứng cổ', E("S.coin")==c0 and not E("S.questM.done.includes('m_count')"))
    E("bumpQuest('M','m_cost')"); ck('"Cập nhật giá vốn" làm được bất kỳ ngày nào', E("S.questM.done.includes('m_cost')"))
    ck('không lỗi', not errs, errs[:2]); saved=E("localStorage.getItem('petpocket.v1')"); pg.close()
    print('— qua 3 ngày thật —')
    ctx=b.new_context(viewport={'width':390,'height':844}, timezone_id='Asia/Ho_Chi_Minh'); pg=ctx.new_page(); errs=[]; pg.on('pageerror',lambda e:errs.append(str(e)[:140]))
    pg.clock.install(time=datetime.datetime(2026,10,14,18,0,tzinfo=VN))
    pg.add_init_script("if(!sessionStorage.getItem('x')){localStorage.setItem('petpocket.v1', %s);sessionStorage.setItem('x','1')}" % json.dumps(saved))
    pg.goto(GAME); pg.wait_for_timeout(1500); E=lambda j: pg.evaluate(j)
    ck('trình duyệt thử đang ở 18 giờ', E("new Date().getHours()")==18, E("new Date().getHours()"))
    E("claim('close')"); ck('18 giờ: "Đóng ca" tick được', E("S.quest.done.includes('close')"))
    E("(()=>{S.qset={eod:20};save()})()"); ck('đổi giờ cuối ngày sang 20:00: giờ này chưa tick được "Kiểm kho cuối ngày"', E("(()=>{claim('stock');return !S.quest.done.includes('stock')})()"))
    E("(()=>{S.qset={eod:17};save()})()")
    for d in [15,16]:
        pg.clock.set_fixed_time(datetime.datetime(2026,10,d,18,0,tzinfo=VN)); E("bumpQuest('W','w_stock')")
    ck('kiểm kho ngày 14, 15, 16: đủ 3/3, nhận thưởng', E("S.questW.done.includes('w_stock')"), E("S.questW.prog.w_stock"))
    pg.clock.set_fixed_time(datetime.datetime(2026,10,26,9,0,tzinfo=VN)); c0=E("S.coin"); e0=E("(S.eggs||[]).length")
    E("bumpQuest('M','m_count')"); ck('ngày 26: "Kiểm kê cuối tháng" mở, nhận xu và trứng cổ', E("S.coin")>c0 and E("(S.eggs||[]).length")==e0+1)
    ck('không lỗi', not errs, errs[:2]); pg.close()

    print('— chuồng và kho —')
    pg,errs=page_at(b, datetime.datetime(2026,10,14,18,0,tzinfo=VN)); E=lambda j: pg.evaluate(j)
    E("(()=>{S.stash=[0,1,2].map(i=>{const p=makePet();p.stage='adult';p.level=10;p.name='P'+i;return p});invOf().expSeed=40;invOf().recipes=['cam_muoi'];invOf().seeds.dao=3;save();S._etab='barn';go('egg')})()"); pg.wait_for_timeout(500)
    tabs=E("[...document.querySelectorAll('#v-egg .cats button')].map(b=>b.textContent.trim())")
    ck('ba thẻ Lò ấp · Chuồng · Kho', tabs==['Lò ấp','Chuồng · 4','Kho'], tabs)
    ck('thẻ Chuồng: chỉ có pet, không có kho', pg.locator('#v-egg .tmc').count()==4 and 'Kho vật phẩm' not in E("document.getElementById('v-egg').textContent"))
    E("(()=>{S._etab='store';mount()})()"); pg.wait_for_timeout(300)
    t=E("document.getElementById('v-egg').textContent")
    ck('thẻ Kho: có vật phẩm, không có pet', 'Kho vật phẩm' in t and pg.locator('#v-egg .tmc').count()==0)
    ck('thẻ công thức hiện tên, không hiện mã nội bộ', 'cam_muoi' not in t and E("DB.recipeById.cam_muoi.name") in t)
    ck('bỏ ghi chú lỗi thời "ở bản sau"', 'bản sau' not in t)
    print('— hạt kinh nghiệm —')
    E("(()=>{S._etab='barn';mount()})()"); pg.wait_for_timeout(300)
    pg.locator('.tmc div[onclick^="openPetInfo"]').first.click(); pg.wait_for_timeout(500)
    ck('bảng thông tin pet có ô hạt kinh nghiệm', pg.locator('#sheet #expbox').count()==1)
    ck('xem trước: Cấp 10 → Cấp …', 'Cấp 10' in pg.locator('#expbox').inner_text())
    lv_prev=E("expSim(S.stash[0],5).lv"); E("expSet(0,5)"); pg.wait_for_timeout(150)
    ck('chọn 5 hạt: xem trước khớp mô phỏng', f'Cấp {lv_prev}' in pg.locator('#expbox .exppv').inner_text(), pg.locator('#expbox .exppv').inner_text())
    lv0=E("S.stash[0].level"); pg.locator('#expbox button',has_text='Cho ăn').click(); pg.wait_for_timeout(500)
    ck('cho ăn: lên đúng cấp đã xem trước', E("S.stash[0].level")==lv_prev and E("invOf().expSeed")==35, f'{lv0} → {E("S.stash[0].level")}')
    E("(()=>{S.stash[1].level=29;S.stash[1].exp=0;invOf().expSeed=100})()")
    mx=E("expMax(S.stash[1])"); ck('gần cấp 30: không cho dùng quá số hạt cần', mx<100 and E("expSim(S.stash[1],"+str(mx)+").lv")==30 and E("expSim(S.stash[1],"+str(mx-1)+").lv")<30, f'chỉ cần {mx} hạt')
    E(clean); E("openExpSheet(-1)"); pg.wait_for_timeout(300)
    ck('pet đang nuôi: mở được bảng cho ăn', pg.locator('#sheet #expbox').count()==1)
    E(clean)
    print('— trứng vàng —')
    # tìm đúng nút mua — chữ "Trứng vàng" có sẵn trong danh sách nguồn trứng nên tìm chữ luôn thấy
    E("(()=>{S.perks=(S.perks||[]).filter(x=>x!=='goldshop');S._etab='inc';go('egg')})()"); pg.wait_for_timeout(300)
    ck('chưa đủ sổ sưu tầm: không có nút mua trứng vàng', pg.locator('[onclick="buyEgg(\'golden\')"]').count()==0)
    E("(()=>{S.perks.push('goldshop');mount()})()"); pg.wait_for_timeout(300)
    ck('đủ 100% sổ sưu tầm: có nút mua trứng vàng', pg.locator('[onclick="buyEgg(\'golden\')"]').count()==1)
    E("(()=>{S.coin=5000;mount()})()"); pg.wait_for_timeout(300); e0=E("(S.eggs||[]).length"); pg.locator('[onclick="buyEgg(\'golden\')"]').click(); pg.wait_for_timeout(300)
    ck('mua được trứng vàng giá 3.000 xu', E("S.coin")==2000 and E("(S.eggs||[]).length")==e0+1, E("S.coin"))
    ck('không lỗi', not errs, errs[:2])
    b.close()
print('\n=== '+(f'{len(F)} HỎNG: {F}' if F else 'TOÀN BỘ ĐẠT')+' ===')
sys.exit(1 if F else 0)
